// This file was automatically generated by jinjaroot. Do not edit directly.
import React from 'react';
// import logo from './logo.svg';
import './App.css';
import MainWindow from './python/surfaceview3/gui/MainWindow/MainWindow';
import { MuiThemeProvider } from '@material-ui/core';
import theme from './theme';
import { BrowserRouter } from 'react-router-dom';
import {KacheryNodeSetup, GoogleSignInSetup} from './python/surfaceview3/gui/labbox';

function App() {
  return (
    <div className="App">
      <MuiThemeProvider theme={theme}>
        <BrowserRouter>
          <GoogleSignInSetup>
            <KacheryNodeSetup>
              <MainWindow />
            </KacheryNodeSetup>
          </GoogleSignInSetup>
        </BrowserRouter>
      </MuiThemeProvider>
    </div>
  )
}

export default App;
